### ISSUE TITLE
A few notes

### ISSUE THREAD

**Issue by mattfarina** [rShetty/multierror#1]
I was just talking with someone about multierrors when i stumbled across this. Glad to see you're using Glide. A few thoughts:

1) What license is this project under? A LICENSE file and maybe a note in the [glide.yaml](http://glide.readthedocs.org/en/latest/glide.yaml/) `license` file would be helpful.

2) The readme says the import is:

```
import "github.com/multierror"
```

I think this needs to be fixed.

3) In formatting the error there's an optimization. Instead of:

```
var formattedError []string
```

You could use:

```
formattedError := make([]string, len(m. errs))
```

This way the backing array to the slice is the right size from the start.

And, one quick question... why didn't you expose the underlying individual errors the way others, like [codegangsta/cli](https://godoc.org/github.com/codegangsta/cli#MultiError), do?

**Comment by rShetty** [comment]
Thanks for these notes @mattfarina 

The project is not licensed currently, will be adding a license soon. Thanks.

> why didn't you expose the underlying individual errors the way others, like codegangsta/cli, do?

No specific reason as such, I could not think of any use case/scenario where exposing errors would be useful. Do you have any example in mind ? 

Thanks for pointing out other concerns in the code too, will be looking into those and soon be fixing them.
